# Foreword {-}

I consider myself very fortunate to have worked with all three of the authors. They are smart and humble, and I owe much of my professional development to their examples and guidance. Uday instilled in me a deep knowledge of best practices for data science and how to be an effective leader, Ken mentored me with conversations on deep learning, and Mitch and I have spent countless hours in deep technical discussions about the best way to approach complex problems, implement production models, and make coffee. I couldn’t be more thrilled to see this book materialize from their incredible knowledge and hard work.

I've been interested in causality ever since I picked up _The Book of Why_ (thanks for the recommendation, Mitch!). As a nerd, I love to read about theory, but the practical side of me isn’t satisfied until I try things out. Unfortunately, it's difficult to go from theory to practice in causality, and the resources to do so have been limited. This book fits that need perfectly. _Applied Causal Inference_ is a well-written and thorough deep dive into the subject, and while it gives a comprehensive overview of the history and theory (plus suggests plenty of resources for additional reading), where it really shines is in its practicality. There are numerous concrete examples and illustrations in every chapter that make this complex subject easy to understand and apply to different domains. The case studies are well-designed, engaging, and give a fantastic opportunity for hands-on learning. The open-source tooling used is accessible and the problems addressed are real-world examples and data.

This book tackles incorporating causality into various complex machine learning applications, such as natural language processing, computer vision, time-series analysis, and reinforcement learning. It also includes a chapter on algorithmic bias and model fairness, and how causality can be used to understand and quantify the direct/indirect effects of that bias. Training ethical machine learning models is critical, and this will empower you to add causal techniques to your toolkit.

This book has been foundational for me in growing my knowledge of causality and giving me the tools to try it out. If you're a data scientist or in a related field, you should read this book! It will help you gain a deeper understanding of causality - what it is, why you should care about it, and most importantly how to go from theory to putting it into practice.

<cite>Christi French, Ph.D.<br>Chief Data Scientist, Azra AI</cite>