name: Render and Deploy Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # - name: Cache R packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-r-${{ hashFiles('.github/r-dependencies') }}
      #     restore-keys: ${{ runner.os }}-r-

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("bookdown", "tidyverse", "gridExtra"))'

      - name: Render Book HTML for GH Pages
        run: |
          cd bookdown
          Rscript -e 'bookdown::render_book()'

      - uses: actions/upload-artifact@v3
        with:
          name: book
          path: bookdown/_book

      # - name: Render PDF
      #   run: Rscript -e 'bookdown::render_book(output=bookdown::pdf_book())'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check site repo
        uses: actions/checkout@v3
        with:
          repository: appliedcausalinference/appliedcausalinference.github.io
          path: appliedcausalinference.github.io
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: book
          path: book

      - name: Copy book artifact
        run: cp -r book/* appliedcausalinference.github.io/

      - name: Get branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      - name: Commit and push changes
        run: |
          cd appliedcausalinference.github.io
          git config user.name "Ken Graham"
          git config user.email klgraham.github@proton.me
          git add .
          git commit -m "Update from "${{ env.branch_name }}" branch"
          git push

