name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R dependencies for Quarto
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::knitr
            any::rmarkdown
            any::tidyverse
            any::gridExtra

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: quarto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}